export type FieldAlias = {
  path: string;
  aliases: string[];
};

export const fieldAliases: FieldAlias[] = [
  { path: 'personal.fullNameEnglish', aliases: ['applicant name', 'candidate name', 'name of applicant', 'full name', 'name english', 'english name', 'name in english', 'applicant name english'] },
  { path: 'personal.fullNameBangla', aliases: ['name bangla', 'bangla name', 'name in bangla', 'name bengali', 'applicant name bangla', 'candidate name bangla', 'বাংলা নাম', 'নাম বাংলায়', 'নাম বাংলায়', 'প্রার্থীর নাম', 'আবেদনকারীর নাম', 'প্রার্থীর নাম বাংলা', 'আবেদনকারীর নাম বাংলা'] },
  { path: 'personal.fatherNameEnglish', aliases: ['father name', "father's name", 'name of father', 'father', 'father name english', "father's name english", 'father name in english'] },
  { path: 'personal.fatherNameBangla', aliases: ['father name bangla', "father's name bangla", 'father name bengali', 'father name in bangla', 'পিতার নাম', 'পিতার নাম বাংলা', 'পিতার নাম বাংলায়', 'পিতার নাম বাংলায়'] },
  { path: 'personal.motherNameEnglish', aliases: ['mother name', "mother's name", 'name of mother', 'mother', 'mother name english', "mother's name english", 'mother name in english'] },
  { path: 'personal.motherNameBangla', aliases: ['mother name bangla', "mother's name bangla", 'mother name bengali', 'mother name in bangla', 'মাতার নাম', 'মাতার নাম বাংলা', 'মাতার নাম বাংলায়', 'মাতার নাম বাংলায়'] },
  { path: 'personal.dateOfBirth', aliases: ['date of birth', 'dob', 'birth date', 'জন্ম তারিখ'] },
  { path: 'personal.gender', aliases: ['gender', 'sex', 'লিঙ্গ'] },
  { path: 'personal.religion', aliases: ['religion', 'ধর্ম'] },
  { path: 'personal.nationality', aliases: ['nationality', 'জাতীয়তা'] },
  { path: 'personal.maritalStatus', aliases: ['marital status', 'married status', 'বৈবাহিক অবস্থা'] },
  { path: 'identification.nationalId.number', aliases: ['nid', 'national id', 'national id number', 'national identity', 'জাতীয় পরিচয়পত্র', 'এনআইডি'] },
  { path: 'identification.birthRegistration.number', aliases: ['birth registration', 'birth certificate', 'birth registration number', 'জন্ম নিবন্ধন', 'জন্ম নিবন্ধন নম্বর'] },
  { path: 'identification.passport.number', aliases: ['passport', 'passport number', 'পাসপোর্ট', 'পাসপোর্ট নম্বর'] },
  { path: 'contact.mobileNumber', aliases: ['mobile', 'mobile number', 'phone', 'phone number', 'contact number', 'মোবাইল', 'মোবাইল নম্বর', 'ফোন'] },
  { path: 'contact.email', aliases: ['email', 'e-mail', 'email address', 'ইমেইল'] },
  { path: 'contact.alternativeMobile', aliases: ['alternative mobile', 'alternate mobile', 'emergency phone', 'optional mobile'] },
  { path: 'address.presentAddress.careOf', aliases: ['present care of', 'care of present', 'c/o present', 'বর্তমান ঠিকানা care of'] },
  { path: 'address.presentAddress.villageRoadHouse', aliases: ['present address', 'present village', 'present road', 'present house', 'village road house', 'বর্তমান ঠিকানা', 'গ্রাম রাস্তা বাড়ি'] },
  { path: 'address.presentAddress.district', aliases: ['present district', 'district present', 'current district', 'বর্তমান জেলা'] },
  { path: 'address.presentAddress.upazila', aliases: ['present upazila', 'present thana', 'current upazila', 'বর্তমান উপজেলা', 'বর্তমান থানা'] },
  { path: 'address.presentAddress.postOffice', aliases: ['present post office', 'post office present', 'বর্তমান ডাকঘর'] },
  { path: 'address.presentAddress.postCode', aliases: ['present post code', 'present postcode', 'present postal code', 'বর্তমান পোস্ট কোড'] },
  { path: 'address.permanentAddress.careOf', aliases: ['permanent care of', 'care of permanent', 'c/o permanent', 'স্থায়ী ঠিকানা care of'] },
  { path: 'address.permanentAddress.villageRoadHouse', aliases: ['permanent address', 'permanent village', 'permanent road', 'permanent house', 'স্থায়ী ঠিকানা'] },
  { path: 'address.permanentAddress.district', aliases: ['permanent district', 'district permanent', 'স্থায়ী জেলা'] },
  { path: 'address.permanentAddress.upazila', aliases: ['permanent upazila', 'permanent thana', 'স্থায়ী উপজেলা', 'স্থায়ী থানা'] },
  { path: 'address.permanentAddress.postOffice', aliases: ['permanent post office', 'স্থায়ী ডাকঘর'] },
  { path: 'address.permanentAddress.postCode', aliases: ['permanent post code', 'permanent postcode', 'permanent postal code', 'স্থায়ী পোস্ট কোড'] },
  { path: 'quota.quotaType', aliases: ['quota', 'quota type', 'কোটা'] },
  { path: 'education.ssc.examination', aliases: ['ssc examination', 'ssc exam', 'secondary examination'] },
  { path: 'education.ssc.board', aliases: ['ssc board', 'secondary board'] },
  { path: 'education.ssc.rollNumber', aliases: ['ssc roll', 'ssc roll number'] },
  { path: 'education.ssc.resultType', aliases: ['ssc result type', 'ssc grade type'] },
  { path: 'education.ssc.resultValue', aliases: ['ssc result', 'ssc gpa', 'ssc cgpa', 'secondary result'] },
  { path: 'education.ssc.groupSubject', aliases: ['ssc group', 'ssc subject', 'secondary group'] },
  { path: 'education.ssc.passingYear', aliases: ['ssc passing year', 'ssc year', 'secondary passing year'] },
  { path: 'education.hsc.examination', aliases: ['hsc examination', 'hsc exam', 'higher secondary examination'] },
  { path: 'education.hsc.board', aliases: ['hsc board', 'higher secondary board'] },
  { path: 'education.hsc.rollNumber', aliases: ['hsc roll', 'hsc roll number'] },
  { path: 'education.hsc.resultType', aliases: ['hsc result type', 'hsc grade type'] },
  { path: 'education.hsc.resultValue', aliases: ['hsc result', 'hsc gpa', 'hsc cgpa', 'higher secondary result'] },
  { path: 'education.hsc.groupSubject', aliases: ['hsc group', 'hsc subject', 'higher secondary group'] },
  { path: 'education.hsc.passingYear', aliases: ['hsc passing year', 'hsc year', 'higher secondary passing year'] },
  { path: 'education.bachelor.examination', aliases: ['graduation examination', 'bachelor examination', 'degree examination'] },
  { path: 'education.bachelor.university', aliases: ['graduation university', 'bachelor university', 'university'] },
  { path: 'education.bachelor.degree', aliases: ['graduation degree', 'bachelor degree', 'degree name'] },
  { path: 'education.bachelor.subject', aliases: ['graduation subject', 'bachelor subject', 'major subject'] },
  { path: 'education.bachelor.resultType', aliases: ['graduation result type', 'bachelor result type'] },
  { path: 'education.bachelor.resultValue', aliases: ['graduation result', 'bachelor result', 'graduation cgpa'] },
  { path: 'education.bachelor.passingYear', aliases: ['graduation passing year', 'bachelor passing year'] },
  { path: 'education.bachelor.courseDuration', aliases: ['graduation duration', 'bachelor duration', 'course duration'] },
  { path: 'education.masters.examination', aliases: ['masters examination', 'master examination'] },
  { path: 'education.masters.university', aliases: ['masters university', 'master university'] },
  { path: 'education.masters.degree', aliases: ['masters degree', 'master degree'] },
  { path: 'education.masters.subject', aliases: ['masters subject', 'master subject'] },
  { path: 'education.masters.resultValue', aliases: ['masters result', 'masters cgpa', 'master result'] },
  { path: 'education.masters.passingYear', aliases: ['masters passing year', 'master passing year'] },
  { path: 'education.mphil.result', aliases: ['mphil result', 'm phil result'] },
  { path: 'education.phd.thesisTitle', aliases: ['phd thesis', 'thesis title', 'dissertation title'] },
  { path: 'training.0.trainingName', aliases: ['training name', 'training title', 'course name'] },
  { path: 'training.0.institution', aliases: ['training institution', 'training institute'] },
  { path: 'training.0.duration', aliases: ['training duration'] },
  { path: 'training.0.completionYear', aliases: ['training year', 'completion year'] },
  { path: 'experiences.0.organization', aliases: ['organization', 'employer', 'office name', 'experience organization'] },
  { path: 'experiences.0.designation', aliases: ['designation', 'post held', 'job title'] },
  { path: 'experiences.0.employmentType', aliases: ['employment type', 'job type', 'service type'] },
  { path: 'experiences.0.startDate', aliases: ['start date', 'joining date', 'from date'] },
  { path: 'experiences.0.endDate', aliases: ['end date', 'to date', 'last date'] },
  { path: 'experiences.0.jobDescription', aliases: ['job description', 'responsibility', 'duties'] },
  { path: 'publications.0.title', aliases: ['publication title', 'research title', 'article title'] },
  { path: 'publications.0.journal', aliases: ['journal', 'journal name'] },
  { path: 'publications.0.publisher', aliases: ['publisher'] },
  { path: 'publications.0.publicationDate', aliases: ['publication date'] }
];

export const blockedFieldAliases = [
  'captcha',
  'security code',
  'verification code',
  'declaration',
  'i agree',
  'submit',
  'final submit',
  'payment',
  'upload',
  'photo upload',
  'signature upload',
  'ক্যাপচা',
  'ঘোষণা',
  'জমা দিন'
];
